version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: promptr-pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=promptr
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql
    networks:
      - promptr-network

  redis:
    image: redis:alpine
    container_name: promptr-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - promptr-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: promptr-server
    ports:
      - '8000:8000'
    environment:
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/promptr
      - DATABASE_NAME=promptr
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis
    networks:
      - promptr-network

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: promptr-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/promptr
      - BACKEND_URL=http://server:8000
    env_file:
      - ./web/.env
    depends_on:
      - postgres
      - server
    networks:
      - promptr-network

volumes:
  pg-data:
  redis-data:

networks:
  promptr-network:
    driver: bridge
