"""remove_learning_style

Revision ID: bd36f4ae558d
Revises: efd72ac925a3
Create Date: 2026-06-04 14:36:29.669566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd36f4ae558d"
down_revision: Union[str, Sequence[str], None] = "efd72ac925a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "learning_style")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column(
            "learning_style", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
